### ISSUE TITLE
IE 10

### ISSUE THREAD

**Issue by MeghaAparanji** [davedupplaw/jquery.thermometer#1]
Hello,

is Jquery SVG thermometer plugin is supported in IE 10? When I used this, page is flashing in IE 10. Help me out to use this in IE 10.

Thanks

**Comment by davedupplaw** [comment]
I'll be honest, I've never tried it in IE10, and there looks to be quite a few issues with SVG in IE <= 11. I'll try to find some time to take a look.

**Comment by theAngryCoder** [comment]
Hi @davedupplaw !

I have apparently fixed the issue. The problem is with the SVG file itself.

**Comment by davedupplaw** [comment]
Cool. I'd got as far as working out it was a problem with the SVG but hadn't fixed it.  Feel free to push the change in, if it works in other browers.

**Comment by theAngryCoder** [comment]
@davedupplaw - Yes, I tested it on IE10, IE11, Chrome, and Firefox. Will send in a push request soon.

**Comment by theAngryCoder** [comment]
@MeghaNaveen - Please check if it works for you now and consider closing the bug. Thanks!

**Comment by MeghaAparanji** [comment]
@theAngryCoder Yes its working fine now in all possible browsers. Thanks. Closing this bug.
